RPC Web Socket - Example JS/HTML Page
Segs/WebUI pull request #12
Opened 2018-10-20 22:15 UTC by miles200

-Add an example JS/HTML page for utilising WebSocket with AdminRPC 

Requires the latest code from SEGS/develop and AuthServer running

2018-10-21 06:45 UTC, dracc requested changes
Please fix the indentation and move `<body>`, apart from that it looks mighty fine. Great work @miles200!

2018-10-21 06:45 UTC, dracc commented on Examples/RPCWebSocketTest.html
> +<body>
Pretty unconventional to put `<body>` inside `<head>`, normally this section would be below `</head>`, hence the names. :)

2018-10-21 06:45 UTC, dracc commented on Examples/RPCWebSocketTest.html
> +<style>
What happened to the indentation?

2018-10-21 19:15 UTC, miles200 commented
@dracc Hey, I've made these changes would you mind checking? Thanks!

2018-10-31 13:31 UTC, dracc commented
Nitpicking: `<script>` tag outside of `<head>`. Doesn't really matter as this will mostly be instructional for how to implement RPC towards the server.

Looks to me like this is ready to be merged. Great job @miles200 !

2018-11-01 00:19 UTC, merged